// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRlNUUdicj3CAW9qsxYRh0b1Gl16SZIo4',
    appId: '1:656390808211:web:e64f2f1b8f710d4e2d2366',
    messagingSenderId: '656390808211',
    projectId: 'fresh-veg-app-6ca54',
    authDomain: 'fresh-veg-app-6ca54.firebaseapp.com',
    storageBucket: 'fresh-veg-app-6ca54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAYiyIyafrjax8u3e8zi58t_BRx6bCJI',
    appId: '1:656390808211:android:2cdcb01fd91850f92d2366',
    messagingSenderId: '656390808211',
    projectId: 'fresh-veg-app-6ca54',
    storageBucket: 'fresh-veg-app-6ca54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcdZbVoYRaKg1PINaVQOpDh2GU-caShtY',
    appId: '1:656390808211:ios:345b03a31770a59b2d2366',
    messagingSenderId: '656390808211',
    projectId: 'fresh-veg-app-6ca54',
    storageBucket: 'fresh-veg-app-6ca54.firebasestorage.app',
    iosClientId: '656390808211-epkjf5ufvr56feme2g727rhgv9mb7ko3.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcdZbVoYRaKg1PINaVQOpDh2GU-caShtY',
    appId: '1:656390808211:ios:345b03a31770a59b2d2366',
    messagingSenderId: '656390808211',
    projectId: 'fresh-veg-app-6ca54',
    storageBucket: 'fresh-veg-app-6ca54.firebasestorage.app',
    iosClientId: '656390808211-epkjf5ufvr56feme2g727rhgv9mb7ko3.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRlNUUdicj3CAW9qsxYRh0b1Gl16SZIo4',
    appId: '1:656390808211:web:3ea8a405c26a782e2d2366',
    messagingSenderId: '656390808211',
    projectId: 'fresh-veg-app-6ca54',
    authDomain: 'fresh-veg-app-6ca54.firebaseapp.com',
    storageBucket: 'fresh-veg-app-6ca54.firebasestorage.app',
  );

}